title: Picture Perfect Creations
logo: assest/img/headshot_circle.png
description: Capturing moments
show download: true
theme: pages-themes/time-machine@v0.2.0
# add this line to the plugins list if you already have one
